var RESTClient = require('./rest').Client;

var Monitor = exports.Monitor = function(conf, logger) {
  if (conf.name !== 'huahin_mrv1')
    throw "monitor name mismatch for huahin_mrv1:" + conf.name;

  this.logger = logger;
  this._client = new RESTClient(conf.host, conf.port);
};

Monitor.prototype.end = function(){
};

Monitor.prototype.supports = function(operation){
  switch (operation) {
  case 'status':
  case 'kill':
    return true;
  }
  throw "unknown operation name (for huahin_mrv1.Monitor):" + operation;
};

function convertStatus(status) {
   // detail status object by huahin manager 0.2.2 mrv1
  /*
  var data = {
    configuration: {
     // job configuration properties. for full list, see end of this file
     // ...
     'hive.query.id': 'hive_20130411160606_46b1b669-3a64-4174-899e-bb1bf53e90db',
     'hive.query.string':
      '--- 3578d8d4 SELECT count(*) AS cnt FROM access_log WHERE (service=\'blog\' OR service=\'blogimg\') AND yyyymmdd=\'20130410\'',
    },
    groups:
    { 'File System Counters': [Object],
      'Job Counters ': [Object],
      'Map-Reduce Framework': [Object],
      'org.apache.hadoop.hive.ql.exec.MapOperator$Counter': [Object],
      'org.apache.hadoop.mapreduce.lib.input.FileInputFormatCounter': [Object] },
    jobid: 'job_201304011701_1912',
    name: 'shib-3578d8d4f5a1812de7a7714f5b108776',
    state: 'RUNNING',
    priority: 'NORMAL',
    mapComplete: '89.014534%',
    reduceComplete: '29.147774%',
    schedulingInfo: 'NA',
    startTime: 'Thu Apr 11 16:06:40 JST 2013',
    trackingURL: 'http://master.hadoop.local:50030/jobdetails.jsp?jobid=job_201304011701_1912',
    jobFile: 'hdfs://namenodehaclustername/mapred/staging/hive/.staging/job_201304011701_1912/job.xml',
    user: 'hive' }
  */
  /*
  var returnedValus = {
    jobid: 'job_201304011701_1912',
    name: 'shib-3578d8d4f5a1812de7a7714f5b108776',
    priority: 'NORMAL',
    state: 'RUNNING',
    trackingURL: 'http://master.hadoop.local:50030/jobdetails.jsp?jobid=job_201304011701_1912',
    startTime: 'Thu Apr 11 2013 16:06:40 (JST)',
    mapComplete: 89,
    reduceComplete: 29,
    hiveQueryId: 'hive_20130411160606_46b1b669-3a64-4174-899e-bb1bf53e90db',
    hiveQueryString: 'SELECT ...'
  };
   */
  if (status === undefined) {
    return null;
  }
  var retval = {};

  retval['jobid'] = status['jobid'];
  retval['name'] = status['name'];
  retval['priority'] = status['priority'];
  retval['state'] = status['state'];
  retval['trackingURL'] = status['trackingURL'];

  retval['startTime'] = (function(sourceDate){
    // convert for `new Date(string)` acceptable format
    // 'Thu Apr 11 16:06:40 JST 2013' -> 'Thu Apr 11 2013 16:06:40 (JST)'

    // [1]Weekday, [2]Month, [3]Day, [4]Time, [5]TimeZone, [6]Year
    var match = /^([A-Z][a-z]{2}) ([A-Z][a-z]{2}) (\d+) (\d\d:\d\d:\d\d) ([a-zA-Z]+) (\d+)$/.exec(sourceDate);
    if (! match) { return null; }
    // -> [1]Weekday, [2]Month, [3]Day, [6]Year, [4]Time, ([5]TimeZone)
    return [match[1], match[2], match[3], match[6], match[4], '(' + match[5] + ')'].join(' ');
  })(status['startTime']);

  retval['mapComplete'] = (status['mapComplete'] ? parseInt(status['mapComplete']) : null);
  retval['reduceComplete'] = (status['reduceComplete'] ? parseInt(status['reduceComplete']) : null);

  retval['hiveQueryId'] = (status['configuration'] || {})['hive.query.id'];
  retval['hiveQueryString'] = (status['configuration'] || {})['hive.query.string'];

  return retval;
};

Monitor.prototype.status = function(jobname, callback){
  var client = this._client;
  client.listAll(function(err, result){
    if (err || !result) { callback(err, null); return; }

    var jobid = null;
    result.forEach(function(job){
      if (job.name === jobname)
        jobid = job.jobid;
    });
    if (!jobid) { callback(null, null); return; }

    client.detail(jobid, function(err, data){
      if (err) { callback(err); return; }
      callback(null, convertStatus(data));
    });
  });
};

Monitor.prototype.kill = function(jobid, callback){
  this._client.kill(jobid, callback);
};

/*
  { 'datanucleus.autoCreateSchema': 'true',
    'datanucleus.autoCreateTables': 'true',
    'datanucleus.autoStartMechanismMode': 'checked',
    'datanucleus.cache.level2': 'false',
    'datanucleus.cache.level2.type': 'none',
    'datanucleus.connectionPoolingType': 'DBCP',
    'datanucleus.fixedDatastore': 'true',
    'datanucleus.identifierFactory': 'datanucleus',
    'datanucleus.plugin.pluginRegistryBundleCheck': 'LOG',
    'datanucleus.storeManagerType': 'rdbms',
    'datanucleus.transactionIsolation': 'repeatable-read',
    'datanucleus.validateColumns': 'false',
    'datanucleus.validateConstraints': 'false',
    'datanucleus.validateTables': 'false',
    'datanucleus.valuegeneration.transactionIsolation': 'repeatable-read',
    'dfs.block.access.key.update.interval': '600',
    'dfs.block.access.token.enable': 'false',
    'dfs.block.access.token.lifetime': '600',
    'dfs.blockreport.initialDelay': '0',
    'dfs.blockreport.intervalMsec': '21600000',
    'dfs.blocksize': '256m',
    'dfs.bytes-per-checksum': '512',
    'dfs.client-write-packet-size': '65536',
    'dfs.client.block.write.replace-datanode-on-failure.enable': 'true',
    'dfs.client.block.write.replace-datanode-on-failure.policy': 'DEFAULT',
    'dfs.client.block.write.retries': '3',
    'dfs.client.failover.connection.retries': '0',
    'dfs.client.failover.connection.retries.on.timeouts': '0',
    'dfs.client.failover.max.attempts': '15',
    'dfs.client.failover.proxy.provider.namenodehaclustername': 'org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider',
    'dfs.client.failover.sleep.base.millis': '500',
    'dfs.client.failover.sleep.max.millis': '15000',
    'dfs.client.file-block-storage-locations.num-threads': '10',
    'dfs.client.file-block-storage-locations.timeout': '60',
    'dfs.client.https.keystore.resource': 'ssl-client.xml',
    'dfs.client.https.need-auth': 'false',
    'dfs.client.use.datanode.hostname': 'false',
    'dfs.datanode.address': '0.0.0.0:50010',
    'dfs.datanode.balance.bandwidthPerSec': '3145728',
    'dfs.datanode.data.dir': 'file:///var/hadoop/disk01/dfs/dn, file:///var/hadoop/disk02/dfs/dn, file:///var/hadoop/disk03/dfs/dn, file:///var/hadoop/disk04/dfs/dn',
    'dfs.datanode.data.dir.perm': '700',
    'dfs.datanode.directoryscan.interval': '21600',
    'dfs.datanode.directoryscan.threads': '1',
    'dfs.datanode.dns.interface': 'default',
    'dfs.datanode.dns.nameserver': 'default',
    'dfs.datanode.drop.cache.behind.reads': 'false',
    'dfs.datanode.drop.cache.behind.writes': 'false',
    'dfs.datanode.du.reserved': '10737418240',
    'dfs.datanode.failed.volumes.tolerated': '0',
    'dfs.datanode.handler.count': '10',
    'dfs.datanode.hdfs-blocks-metadata.enabled': 'true',
    'dfs.datanode.http.address': '0.0.0.0:50075',
    'dfs.datanode.https.address': '0.0.0.0:50475',
    'dfs.datanode.ipc.address': '0.0.0.0:50020',
    'dfs.datanode.max.transfer.threads': '8192',
    'dfs.datanode.readahead.bytes': '4193404',
    'dfs.datanode.sync.behind.writes': 'false',
    'dfs.datanode.use.datanode.hostname': 'false',
    'dfs.default.chunk.view.size': '32768',
    'dfs.domain.socket.path': '/var/run/hadoop-hdfs/dn._PORT',
    'dfs.encrypt.data.transfer': 'false',
    'dfs.ha.automatic-failover.enabled': 'false',
    'dfs.ha.fencing.methods': 'shell(/bin/true)',
    'dfs.ha.fencing.ssh.connect-timeout': '30000',
    'dfs.ha.log-roll.period': '120',
    'dfs.ha.namenodes.namenodehaclustername': 'master01,master02',
    'dfs.ha.tail-edits.period': '60',
    'dfs.heartbeat.interval': '3',
    'dfs.https.enable': 'false',
    'dfs.https.server.keystore.resource': 'ssl-server.xml',
    'dfs.image.compress': 'false',
    'dfs.image.compression.codec': 'org.apache.hadoop.io.compress.DefaultCodec',
    'dfs.image.transfer.bandwidthPerSec': '0',
    'dfs.journalnode.edits.dir': '/var/hadoop/disk01/dfs/jn',
    'dfs.journalnode.http-address': '0.0.0.0:8480',
    'dfs.journalnode.rpc-address': '0.0.0.0:8485',
    'dfs.namenode.accesstime.precision': '3600000',
    'dfs.namenode.audit.loggers': 'default',
    'dfs.namenode.backup.address': '0.0.0.0:50100',
    'dfs.namenode.backup.http-address': '0.0.0.0:50105',
    'dfs.namenode.checkpoint.check.period': '3600',
    'dfs.namenode.checkpoint.dir': 'file:///var/hadoop/tmp/cache/dfs',
    'dfs.namenode.checkpoint.edits.dir': 'file:///var/hadoop/tmp/cache/dfs',
    'dfs.namenode.checkpoint.period': '3600',
    'dfs.namenode.checkpoint.txns': '40000',
    'dfs.namenode.decommission.interval': '30',
    'dfs.namenode.decommission.nodes.per.interval': '5',
    'dfs.namenode.delegation.key.update-interval': '86400000',
    'dfs.namenode.delegation.token.max-lifetime': '604800000',
    'dfs.namenode.delegation.token.renew-interval': '86400000',
    'dfs.namenode.edits.dir': '${dfs.namenode.name.dir}',
    'dfs.namenode.edits.journal-plugin.qjournal': 'org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager',
    'dfs.namenode.fs-limits.max-component-length': '0',
    'dfs.namenode.fs-limits.max-directory-items': '0',
    'dfs.namenode.handler.count': '20',
    'dfs.namenode.http-address': '0.0.0.0:50070',
    'dfs.namenode.http-address.namenodehaclustername.master01': 'master01.hadoop.local:50070',
    'dfs.namenode.http-address.namenodehaclustername.master02': 'master02.hadoop.local:50070',
    'dfs.namenode.https-address': '0.0.0.0:50470',
    'dfs.namenode.invalidate.work.pct.per.iteration': '0.32f',
    'dfs.namenode.kerberos.internal.spnego.principal': '${dfs.web.authentication.kerberos.principal}',
    'dfs.namenode.logging.level': 'info',
    'dfs.namenode.max.extra.edits.segments.retained': '10000',
    'dfs.namenode.max.objects': '0',
    'dfs.namenode.name.dir': 'file:///var/hadoop/disk01/dfs/nn',
    'dfs.namenode.name.dir.restore': 'false',
    'dfs.namenode.num.checkpoints.retained': '2',
    'dfs.namenode.num.extra.edits.retained': '1000000',
    'dfs.namenode.replication.considerLoad': 'true',
    'dfs.namenode.replication.interval': '3',
    'dfs.namenode.replication.min': '1',
    'dfs.namenode.replication.work.multiplier.per.iteration': '2',
    'dfs.namenode.rpc-address.namenodeclustername.master01': 'master01.hadoop.local:8020',
    'dfs.namenode.rpc-address.namenodeclustername.master02': 'master02.hadoop.local:8020',
    'dfs.namenode.safemode.extension': '30000',
    'dfs.namenode.safemode.min.datanodes': '0',
    'dfs.namenode.safemode.threshold-pct': '0.999f',
    'dfs.namenode.secondary.http-address': '0.0.0.0:50090',
    'dfs.namenode.shared.edits.dir': 'qjournal://journalnode01.hadoop.local:8485;journalnode02.hadoop.local:8485;journalnode03.hadoop.local:8485/mycluster',
    'dfs.namenode.support.allow.format': 'true',
    'dfs.nameservices': 'namenodehaclustername',
    'dfs.permissions.enabled': 'false',
    'dfs.permissions.superusergroup': 'hadoop',
    'dfs.replication': '3',
    'dfs.replication.max': '512',
    'dfs.secondary.namenode.kerberos.internal.spnego.principal': '${dfs.web.authentication.kerberos.principal}',
    'dfs.stream-buffer-size': '4096',
    'dfs.support.append': 'true',
    'dfs.webhdfs.enabled': 'true',
    'file.blocksize': '67108864',
    'file.bytes-per-checksum': '512',
    'file.client-write-packet-size': '65536',
    'file.replication': '1',
    'file.stream-buffer-size': '4096',
    'fs.AbstractFileSystem.file.impl': 'org.apache.hadoop.fs.local.LocalFs',
    'fs.AbstractFileSystem.hdfs.impl': 'org.apache.hadoop.fs.Hdfs',
    'fs.AbstractFileSystem.viewfs.impl': 'org.apache.hadoop.fs.viewfs.ViewFs',
    'fs.automatic.close': 'true',
    'fs.defaultFS': 'hdfs://namenodehaclustername',
    'fs.df.interval': '60000',
    'fs.ftp.host': '0.0.0.0',
    'fs.ftp.host.port': '21',
    'fs.har.impl': 'org.apache.hadoop.hive.shims.HiveHarFileSystem',
    'fs.permissions.umask-mode': '022',
    'fs.s3.block.size': '67108864',
    'fs.s3.buffer.dir': '${hadoop.tmp.dir}/s3',
    'fs.s3.maxRetries': '4',
    'fs.s3.sleepTimeSeconds': '10',
    'fs.s3n.block.size': '67108864',
    'fs.trash.checkpoint.interval': '0',
    'fs.trash.interval': '0',
    'ftp.blocksize': '67108864',
    'ftp.bytes-per-checksum': '512',
    'ftp.client-write-packet-size': '65536',
    'ftp.replication': '3',
    'ftp.stream-buffer-size': '4096',
    'group.name': 'hive',
    'ha.failover-controller.cli-check.rpc-timeout.ms': '20000',
    'ha.failover-controller.graceful-fence.connection.retries': '1',
    'ha.failover-controller.graceful-fence.rpc-timeout.ms': '5000',
    'ha.failover-controller.new-active.rpc-timeout.ms': '60000',
    'ha.health-monitor.check-interval.ms': '1000',
    'ha.health-monitor.connect-retry-interval.ms': '1000',
    'ha.health-monitor.rpc-timeout.ms': '45000',
    'ha.health-monitor.sleep-after-disconnect.ms': '1000',
    'ha.zookeeper.acl': 'world:anyone:rwcda',
    'ha.zookeeper.parent-znode': '/hadoop-ha',
    'ha.zookeeper.quorum': 'jornalnode01.hadoop.local,journalnode02.hadoop.local,journalnode03.hadoop.local',
    'ha.zookeeper.session-timeout.ms': '5000',
    'hadoop.bin.path': '//usr/lib/hadoop/bin/hadoop',
    'hadoop.common.configuration.version': '0.23.0',
    'hadoop.conf.dir': '/etc/hadoop/conf',
    'hadoop.fuse.connection.timeout': '300',
    'hadoop.fuse.timer.period': '5',
    'hadoop.hdfs.configuration.version': '1',
    'hadoop.http.authentication.kerberos.keytab': '${user.home}/hadoop.keytab',
    'hadoop.http.authentication.kerberos.principal': 'HTTP/_HOST@LOCALHOST',
    'hadoop.http.authentication.signature.secret.file': '${user.home}/hadoop-http-auth-signature-secret',
    'hadoop.http.authentication.simple.anonymous.allowed': 'true',
    'hadoop.http.authentication.token.validity': '36000',
    'hadoop.http.authentication.type': 'simple',
    'hadoop.http.filter.initializers': 'org.apache.hadoop.http.lib.StaticUserWebFilter',
    'hadoop.http.staticuser.user': 'webuser,webgroup',
    'hadoop.jetty.logs.serve.aliases': 'true',
    'hadoop.job.history.location': '/mrv1-history',
    'hadoop.kerberos.kinit.command': 'kinit',
    'hadoop.proxyuser.httpfs.groups': '*',
    'hadoop.proxyuser.httpfs.hosts': '*',
    'hadoop.relaxed.worker.version.check': 'true',
    'hadoop.rpc.protection': 'authentication',
    'hadoop.rpc.socket.factory.class.default': 'org.apache.hadoop.net.StandardSocketFactory',
    'hadoop.security.authentication': 'simple',
    'hadoop.security.authorization': 'false',
    'hadoop.security.group.mapping': 'org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback',
    'hadoop.security.group.mapping.ldap.search.attr.group.name': 'cn',
    'hadoop.security.group.mapping.ldap.search.attr.member': 'member',
    'hadoop.security.group.mapping.ldap.search.filter.group': '(objectClass=group)',
    'hadoop.security.group.mapping.ldap.search.filter.user': '(&(objectClass=user)(sAMAccountName={0}))',
    'hadoop.security.group.mapping.ldap.ssl': 'false',
    'hadoop.security.groups.cache.secs': '300',
    'hadoop.security.instrumentation.requires.admin': 'false',
    'hadoop.security.uid.cache.secs': '14400',
    'hadoop.skip.worker.version.check': 'false',
    'hadoop.ssl.client.conf': 'ssl-client.xml',
    'hadoop.ssl.enabled': 'false',
    'hadoop.ssl.hostname.verifier': 'DEFAULT',
    'hadoop.ssl.keystores.factory.class': 'org.apache.hadoop.security.ssl.FileBasedKeyStoresFactory',
    'hadoop.ssl.require.client.cert': 'false',
    'hadoop.ssl.server.conf': 'ssl-server.xml',
    'hadoop.tmp.dir': '/var/hadoop/tmp/${user.name}',
    'hadoop.util.hash.type': 'murmur',
    'hadoop.work.around.non.threadsafe.getpwuid': 'false',
    'hive.added.jars.path': 'file:///home/user/woothee.jar,file:///usr/lib/hive/lib/hive-builtins-0.10.0-cdh4.2.0.jar',
    'hive.archive.enabled': 'false',
    'hive.archive.har.parentdir.settable': 'true',
    'hive.auto.convert.join': 'false',
    'hive.auto.progress.timeout': '0',
    'hive.autogen.columnalias.prefix.includefuncname': 'false',
    'hive.autogen.columnalias.prefix.label': '_c',
    'hive.binary.record.max.length': '1000',
    'hive.cli.errors.ignore': 'false',
    'hive.cli.print.current.db': 'false',
    'hive.cli.print.header': 'false',
    'hive.cli.prompt': 'hive',
    'hive.cluster.delegation.token.store.class': 'org.apache.hadoop.hive.thrift.MemoryTokenStore',
    'hive.cluster.delegation.token.store.zookeeper.znode': '/hive/cluster/delegation',
    'hive.conf.validation': 'true',
    'hive.debug.localtask': 'false',
    'hive.default.fileformat': 'TextFile',
    'hive.downloaded.resources.dir': '/tmp/hive/hive_resources',
    'hive.enforce.bucketing': 'false',
    'hive.enforce.bucketmapjoin': 'false',
    'hive.enforce.sorting': 'false',
    'hive.enforce.sortmergebucketmapjoin': 'false',
    'hive.entity.separator': '@',
    'hive.error.on.empty.partition': 'false',
    'hive.exec.compress.intermediate': 'false',
    'hive.exec.compress.output': 'true',
    'hive.exec.concatenate.check.index': 'true',
    'hive.exec.counters.pull.interval': '1000',
    'hive.exec.default.partition.name': '__HIVE_DEFAULT_PARTITION__',
    'hive.exec.drop.ignorenonexistent': 'true',
    'hive.exec.dynamic.partition': 'false',
    'hive.exec.dynamic.partition.mode': 'strict',
    'hive.exec.job.debug.capture.stacktraces': 'true',
    'hive.exec.job.debug.timeout': '30000',
    'hive.exec.list.bucketing.default.dir': 'HIVE_DEFAULT_LIST_BUCKETING_DIR_NAME',
    'hive.exec.local.scratchdir': '/tmp/hive',
    'hive.exec.max.created.files': '100000',
    'hive.exec.max.dynamic.partitions': '1000',
    'hive.exec.max.dynamic.partitions.pernode': '100',
    'hive.exec.mode.local.auto': 'false',
    'hive.exec.mode.local.auto.input.files.max': '4',
    'hive.exec.mode.local.auto.inputbytes.max': '134217728',
    'hive.exec.parallel': 'true',
    'hive.exec.parallel.thread.number': '8',
    'hive.exec.perf.logger': 'org.apache.hadoop.hive.ql.log.PerfLogger',
    'hive.exec.plan': 'hdfs://namenodehaclustername/tmp/hive-hive/hive_2013-04-11_16-06-38_373_6837539457494191559/-mr-10003/ef2e8dfd-6717-4969-a599-42708098c616',
    'hive.exec.rcfile.use.explicit.header': 'true',
    'hive.exec.reducers.bytes.per.reducer': '1000000000',
    'hive.exec.reducers.max': '30',
    'hive.exec.rowoffset': 'false',
    'hive.exec.scratchdir': '/tmp/hive-${user.name}',
    'hive.exec.script.allow.partial.consumption': 'false',
    'hive.exec.script.maxerrsize': '100000',
    'hive.exec.script.trust': 'false',
    'hive.exec.show.job.failure.debug.info': 'true',
    'hive.exec.submitviachild': 'false',
    'hive.exec.tasklog.debug.timeout': '20000',
    'hive.exim.uri.scheme.whitelist': 'hdfs,pfile',
    'hive.fetch.output.serde': 'org.apache.hadoop.hive.serde2.DelimitedJSONSerDe',
    'hive.fetch.task.conversion': 'minimal',
    'hive.fileformat.check': 'true',
    'hive.groupby.mapaggr.checkinterval': '100000',
    'hive.groupby.skewindata': 'false',
    'hive.hadoop.supports.splittable.combineinputformat': 'false',
    'hive.hashtable.initialCapacity': '100000',
    'hive.hashtable.loadfactor': '0.75',
    'hive.hbase.wal.enabled': 'true',
    'hive.heartbeat.interval': '1000',
    'hive.hmshandler.force.reload.conf': 'false',
    'hive.hmshandler.retry.attempts': '1',
    'hive.hmshandler.retry.interval': '1000',
    'hive.hwi.listen.host': '0.0.0.0',
    'hive.hwi.listen.port': '9999',
    'hive.index.compact.binary.search': 'true',
    'hive.index.compact.file.ignore.hdfs': 'false',
    'hive.index.compact.query.max.entries': '10000000',
    'hive.index.compact.query.max.size': '10737418240',
    'hive.input.format': 'org.apache.hadoop.hive.ql.io.CombineHiveInputFormat',
    'hive.input.format.sorted': 'false',
    'hive.insert.into.external.tables': 'true',
    'hive.insert.into.multilevel.dirs': 'false',
    'hive.internal.ddl.list.bucketing.enable': 'false',
    'hive.jobname.length': '50',
    'hive.join.cache.size': '25000',
    'hive.join.emit.interval': '1000',
    'hive.limit.optimize.enable': 'false',
    'hive.limit.optimize.fetch.max': '50000',
    'hive.limit.optimize.limit.file': '10',
    'hive.limit.row.max.size': '100000',
    'hive.lock.manager': 'org.apache.hadoop.hive.ql.lockmgr.zookeeper.ZooKeeperHiveLockManager',
    'hive.lock.mapred.only.operation': 'false',
    'hive.lock.numretries': '100',
    'hive.lock.sleep.between.retries': '60',
    'hive.lockmgr.zookeeper.default.partition.name': '__HIVE_DEFAULT_ZOOKEEPER_PARTITION__',
    'hive.map.aggr': 'true',
    'hive.map.aggr.hash.force.flush.memory.threshold': '0.9',
    'hive.map.aggr.hash.min.reduction': '0.5',
    'hive.map.aggr.hash.percentmemory': '0.5',
    'hive.map.groupby.sorted': 'false',
    'hive.mapjoin.bucket.cache.size': '100',
    'hive.mapjoin.cache.numrows': '25000',
    'hive.mapjoin.check.memory.rows': '100000',
    'hive.mapjoin.followby.gby.localtask.max.memory.usage': '0.55',
    'hive.mapjoin.followby.map.aggr.hash.percentmemory': '0.3',
    'hive.mapjoin.localtask.max.memory.usage': '0.9',
    'hive.mapjoin.size.key': '10000',
    'hive.mapjoin.smalltable.filesize': '25000000',
    'hive.mapper.cannot.span.multiple.partitions': 'false',
    'hive.mapred.local.mem': '0',
    'hive.mapred.mode': 'nonstrict',
    'hive.mapred.partitioner': 'org.apache.hadoop.hive.ql.io.DefaultHivePartitioner',
    'hive.mapred.reduce.tasks.speculative.execution': 'true',
    'hive.mapred.supports.subdirectories': 'false',
    'hive.merge.current.job.has.dynamic.partitions': 'false',
    'hive.merge.input.format.block.level': 'org.apache.hadoop.hive.ql.io.rcfile.merge.RCFileBlockMergeInputFormat',
    'hive.merge.mapfiles': 'true',
    'hive.merge.mapredfiles': 'false',
    'hive.merge.rcfile.block.level': 'true',
    'hive.merge.size.per.task': '256000000',
    'hive.merge.smallfiles.avgsize': '16000000',
    'hive.mergejob.maponly': 'true',
    'hive.metadata.move.exported.metadata.to.trash': 'true',
    'hive.metastore.archive.intermediate.archived': '_INTERMEDIATE_ARCHIVED',
    'hive.metastore.archive.intermediate.extracted': '_INTERMEDIATE_EXTRACTED',
    'hive.metastore.archive.intermediate.original': '_INTERMEDIATE_ORIGINAL',
    'hive.metastore.authorization.storage.checks': 'false',
    'hive.metastore.batch.retrieve.max': '300',
    'hive.metastore.batch.retrieve.table.partition.max': '1000',
    'hive.metastore.cache.pinobjtypes': 'Table,StorageDescriptor,SerDeInfo,Partition,Database,Type,FieldSchema,Order',
    'hive.metastore.client.connect.retry.delay': '1',
    'hive.metastore.client.socket.timeout': '20',
    'hive.metastore.connect.retries': '3',
    'hive.metastore.ds.retry.attempts': '1',
    'hive.metastore.ds.retry.interval': '1000',
    'hive.metastore.event.clean.freq': '0',
    'hive.metastore.event.expiry.duration': '0',
    'hive.metastore.execute.setugi': 'false',
    'hive.metastore.failure.retries': '1',
    'hive.metastore.force.reload.conf': 'false',
    'hive.metastore.fs.handler.class': 'org.apache.hadoop.hive.metastore.HiveMetaStoreFsImpl',
    'hive.metastore.kerberos.principal': 'hive-metastore/_HOST@EXAMPLE.COM',
    'hive.metastore.rawstore.impl': 'org.apache.hadoop.hive.metastore.ObjectStore',
    'hive.metastore.sasl.enabled': 'false',
    'hive.metastore.server.max.threads': '100000',
    'hive.metastore.server.min.threads': '200',
    'hive.metastore.server.tcp.keepalive': 'true',
    'hive.metastore.thrift.framed.transport.enabled': 'false',
    'hive.metastore.warehouse.dir': '/shib/warehouse',
    'hive.multi.insert.move.tasks.share.dependencies': 'false',
    'hive.multigroupby.singlereducer': 'true',
    'hive.optimize.bucketmapjoin': 'false',
    'hive.optimize.bucketmapjoin.sortedmerge': 'false',
    'hive.optimize.cp': 'true',
    'hive.optimize.groupby': 'true',
    'hive.optimize.index.autoupdate': 'false',
    'hive.optimize.index.filter': 'false',
    'hive.optimize.index.filter.compact.maxsize': '-1',
    'hive.optimize.index.filter.compact.minsize': '5368709120',
    'hive.optimize.index.groupby': 'false',
    'hive.optimize.listbucketing': 'false',
    'hive.optimize.metadataonly': 'true',
    'hive.optimize.ppd': 'true',
    'hive.optimize.ppd.storage': 'true',
    'hive.optimize.reducededuplication': 'true',
    'hive.optimize.skewjoin': 'false',
    'hive.optimize.skewjoin.compiletime': 'false',
    'hive.optimize.union.remove': 'false',
    'hive.outerjoin.supports.filters': 'true',
    'hive.ppd.recognizetransivity': 'true',
    'hive.ppd.remove.duplicatefilters': 'true',
    'hive.query.id': 'hive_20130411160606_46b1b669-3a64-4174-899e-bb1bf53e90db',
    'hive.query.result.fileformat': 'TextFile',
    'hive.query.string': '--- 3578d8d4 SELECT count(*) AS cnt FROM access_log WHERE (service=\'blog\' OR service=\'blogimg\') AND yyyymmdd=\'20130410\'',
    'hive.querylog.enable.plan.progress': 'true',
    'hive.querylog.location': '/tmp/hive',
    'hive.querylog.plan.progress.interval': '60000',
    'hive.rework.mapredwork': 'false',
    'hive.sample.seednumber': '0',
    'hive.script.auto.progress': 'false',
    'hive.script.operator.id.env.var': 'HIVE_SCRIPT_OPERATOR_ID',
    'hive.script.operator.truncate.env': 'false',
    'hive.script.recordreader': 'org.apache.hadoop.hive.ql.exec.TextRecordReader',
    'hive.script.recordwriter': 'org.apache.hadoop.hive.ql.exec.TextRecordWriter',
    'hive.script.serde': 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe',
    'hive.security.authenticator.manager': 'org.apache.hadoop.hive.ql.security.HadoopDefaultAuthenticator',
    'hive.security.authorization.enabled': 'false',
    'hive.security.authorization.manager': 'org.apache.hadoop.hive.ql.security.authorization.DefaultHiveAuthorizationProvider',
    'hive.security.metastore.authenticator.manager': 'org.apache.hadoop.hive.ql.security.HadoopDefaultMetastoreAuthenticator',
    'hive.security.metastore.authorization.manager': 'org.apache.hadoop.hive.ql.security.authorization.DefaultHiveMetastoreAuthorizationProvider',
    'hive.server.read.socket.timeout': '10',
    'hive.server.tcp.keepalive': 'true',
    'hive.server2.authentication': 'NONE',
    'hive.server2.enable.impersonation': 'false',
    'hive.server2.thrift.max.worker.threads': '100',
    'hive.server2.thrift.min.worker.threads': '5',
    'hive.server2.thrift.port': '10000',
    'hive.session.id': 'hive_201304111606',
    'hive.session.silent': 'false',
    'hive.skewjoin.key': '100000',
    'hive.skewjoin.mapjoin.map.tasks': '10000',
    'hive.skewjoin.mapjoin.min.split': '33554432',
    'hive.start.cleanup.scratchdir': 'false',
    'hive.stats.atomic': 'false',
    'hive.stats.autogather': 'false',
    'hive.stats.collect.rawdatasize': 'true',
    'hive.stats.collect.tablekeys': 'false',
    'hive.stats.dbclass': 'jdbc:derby',
    'hive.stats.dbconnectionstring': 'jdbc:derby:;databaseName=TempStatsStore;create=true',
    'hive.stats.jdbc.timeout': '30',
    'hive.stats.jdbcdriver': 'org.apache.derby.jdbc.EmbeddedDriver',
    'hive.stats.ndv.error': '20.0',
    'hive.stats.reliable': 'false',
    'hive.stats.retries.max': '0',
    'hive.stats.retries.wait': '3000',
    'hive.support.concurrency': 'false',
    'hive.task.progress': 'false',
    'hive.test.mode': 'false',
    'hive.test.mode.prefix': 'test_',
    'hive.test.mode.samplefreq': '32',
    'hive.transform.escape.input': 'false',
    'hive.udtf.auto.progress': 'false',
    'hive.unlock.numretries': '10',
    'hive.variable.substitute': 'true',
    'hive.variable.substitute.depth': '40',
    'hive.warehouse.subdir.inherit.perms': 'true',
    'hive.zookeeper.clean.extra.nodes': 'false',
    'hive.zookeeper.client.port': '2181',
    'hive.zookeeper.namespace': 'hive_zookeeper_namespace',
    'hive.zookeeper.session.timeout': '600000',
    'io.compression.codecs': 'org.apache.hadoop.io.compress.DefaultCodec,org.apache.hadoop.io.compress.GzipCodec,org.apache.hadoop.io.compress.BZip2Codec,org.apache.hadoop.io.compress.DeflateCodec,org.apache.hadoop.io.compress.SnappyCodec',
    'io.file.buffer.size': '131072',
    'io.map.index.interval': '128',
    'io.map.index.skip': '0',
    'io.mapfile.bloom.error.rate': '0.005',
    'io.mapfile.bloom.size': '1048576',
    'io.native.lib.available': 'true',
    'io.seqfile.compress.blocksize': '1000000',
    'io.seqfile.lazydecompress': 'true',
    'io.seqfile.local.dir': '/path/to/seqfile/local/dir/list',
    'io.seqfile.sorter.recordlimit': '1000000',
    'io.serializations': 'org.apache.hadoop.io.serializer.WritableSerialization,org.apache.hadoop.io.serializer.avro.AvroSpecificSerialization,org.apache.hadoop.io.serializer.avro.AvroReflectSerialization',
    'io.skip.checksum.errors': 'false',
    'io.sort.factor': '10',
    'io.sort.mb': '100',
    'io.sort.record.percent': '0.05',
    'io.sort.spill.percent': '0.80',
    'ipc.client.connect.max.retries': '10',
    'ipc.client.connect.max.retries.on.timeouts': '45',
    'ipc.client.connection.maxidletime': '10000',
    'ipc.client.idlethreshold': '4000',
    'ipc.client.kill.max': '10',
    'ipc.client.tcpnodelay': 'false',
    'ipc.server.listen.queue.size': '128',
    'ipc.server.tcpnodelay': 'false',
    'javax.jdo.PersistenceManagerFactoryClass': 'org.datanucleus.jdo.JDOPersistenceManagerFactory',
    'javax.jdo.option.ConnectionDriverName': 'com.mysql.jdbc.Driver',
    'javax.jdo.option.ConnectionPassword': 'HIVE',
    'javax.jdo.option.ConnectionURL': 'jdbc:mysql://database.metastore.hadoo.local/metastore',
    'javax.jdo.option.ConnectionUserName': 'hive',
    'javax.jdo.option.DetachAllOnCommit': 'true',
    'javax.jdo.option.Multithreaded': 'true',
    'javax.jdo.option.NonTransactionalRead': 'true',
    'job.end.retry.attempts': '0',
    'job.end.retry.interval': '30000',
    'jobclient.completion.poll.interval': '5000',
    'jobclient.output.filter': 'FAILED',
    'jobclient.progress.monitor.poll.interval': '1000',
    'keep.failed.task.files': 'false',
    'kfs.blocksize': '67108864',
    'kfs.bytes-per-checksum': '512',
    'kfs.client-write-packet-size': '65536',
    'kfs.replication': '3',
    'kfs.stream-buffer-size': '4096',
    'local.cache.size': '10737418240',
    'map.sort.class': 'org.apache.hadoop.util.QuickSort',
    'mapred.acls.enabled': 'false',
    'mapred.cache.files': 'hdfs://namenodehacluster/tmp/hive-hive/hive_2013-04-11_16-06-38_373_6837539457494191559/-mr-10003/ef2e8dfd-6717-4969-a599-42708098c616#HIVE_PLANef2e8dfd-6717-4969-a599-42708098c616,hdfs://namenodehacluster/mapred/staging/hive/.staging/job_201304011701_1912/libjars/woothee.jar,hdfs://namenodehaclustername/mapred/staging/hive/.staging/job_201304011701_1912/libjars/hive-builtins-0.10.0-cdh4.2.0.jar',
    'mapred.cache.files.filesizes': '69754,57899,3909',
    'mapred.cache.files.timestamps': '1365663998711,1365663998741,1365663998755',
    'mapred.child.java.opts': '-Xmx2048m',
    'mapred.child.tmp': './tmp',
    'mapred.cluster.map.memory.mb': '-1',
    'mapred.cluster.max.map.memory.mb': '-1',
    'mapred.cluster.max.reduce.memory.mb': '-1',
    'mapred.cluster.reduce.memory.mb': '-1',
    'mapred.committer.job.setup.cleanup.needed': 'false',
    'mapred.compress.map.output': 'false',
    'mapred.create.symlink': 'yes',
    'mapred.disk.healthChecker.interval': '60000',
    'mapred.healthChecker.interval': '60000',
    'mapred.healthChecker.script.timeout': '600000',
    'mapred.heartbeats.in.second': '100',
    'mapred.inmem.merge.threshold': '1000',
    'mapred.input.dir': 'hdfs://namenodehacluster/shib/warehouse/access_log/service=blog/yyyymmdd=20130410,hdfs://namenodehaclustername/shib/warehouse/access_log/service=blogimg/yyyymmdd=20130410',
    'mapred.input.dir.recursive': 'false',
    'mapred.input.format.class': 'org.apache.hadoop.hive.ql.io.CombineHiveInputFormat',
    'mapred.jar': '/mapred/staging/hive/.staging/job_201304011701_1912/job.jar',
    'mapred.job.classpath.files': '/mapred/staging/hive/.staging/job_201304011701_1912/libjars/woothee.jar:/mapred/staging/hive/.staging/job_201304011701_1912/libjars/hive-builtins-0.10.0-cdh4.2.0.jar',
    'mapred.job.map.memory.mb': '-1',
    'mapred.job.name': 'shib-3578d8d4f5a1812de7a7714f5b108776',
    'mapred.job.queue.name': 'default',
    'mapred.job.reduce.input.buffer.percent': '0.0',
    'mapred.job.reduce.memory.mb': '-1',
    'mapred.job.restart.recover': 'true',
    'mapred.job.reuse.jvm.num.tasks': '1',
    'mapred.job.shuffle.input.buffer.percent': '0.70',
    'mapred.job.shuffle.merge.percent': '0.66',
    'mapred.job.tracker': 'master.hadoop.local:8021',
    'mapred.job.tracker.handler.count': '150',
    'mapred.job.tracker.http.address': 'master.hadoop.local:50030',
    'mapred.job.tracker.jobhistory.lru.cache.size': '5',
    'mapred.job.tracker.persist.jobstatus.active': 'false',
    'mapred.job.tracker.persist.jobstatus.dir': '/jobtracker/jobsInfo',
    'mapred.job.tracker.persist.jobstatus.hours': '0',
    'mapred.job.tracker.retiredjobs.cache.size': '1000',
    'mapred.jobtracker.completeuserjobs.maximum': '100',
    'mapred.jobtracker.instrumentation': 'org.apache.hadoop.mapred.JobTrackerMetricsInst',
    'mapred.jobtracker.job.history.block.size': '3145728',
    'mapred.jobtracker.maxtasks.per.job': '-1',
    'mapred.jobtracker.restart.recover': 'false',
    'mapred.jobtracker.taskScheduler': 'org.apache.hadoop.mapred.JobQueueTaskScheduler',
    'mapred.line.input.format.linespermap': '1',
    'mapred.local.dir': '/mapred/local/dir/list',
    'mapred.local.dir.minspacekill': '0',
    'mapred.local.dir.minspacestart': '0',
    'mapred.map.child.log.level': 'INFO',
    'mapred.map.max.attempts': '4',
    'mapred.map.output.compression.codec': 'org.apache.hadoop.io.compress.DefaultCodec',
    'mapred.map.tasks': '2867',
    'mapred.map.tasks.speculative.execution': 'false',
    'mapred.mapoutput.key.class': 'org.apache.hadoop.hive.ql.io.HiveKey',
    'mapred.mapoutput.value.class': 'org.apache.hadoop.io.BytesWritable',
    'mapred.mapper.class': 'org.apache.hadoop.hive.ql.exec.ExecMapper',
    'mapred.max.split.size': '256000000',
    'mapred.max.tracker.blacklists': '4',
    'mapred.max.tracker.failures': '4',
    'mapred.merge.recordsBeforeProgress': '10000',
    'mapred.min.split.size': '1',
    'mapred.min.split.size.per.node': '1',
    'mapred.min.split.size.per.rack': '1',
    'mapred.output.committer.class': 'org.apache.hadoop.hive.shims.HadoopShimsSecure$NullOutputCommitter',
    'mapred.output.compress': 'true',
    'mapred.output.compression.codec': 'org.apache.hadoop.io.compress.GzipCodec',
    'mapred.output.compression.type': 'BLOCK',
    'mapred.output.format.class': 'org.apache.hadoop.hive.ql.io.HiveOutputFormatImpl',
    'mapred.output.key.class': 'org.apache.hadoop.io.Text',
    'mapred.output.value.class': 'org.apache.hadoop.io.Text',
    'mapred.partitioner.class': 'org.apache.hadoop.hive.ql.io.DefaultHivePartitioner',
    'mapred.queue.default.acl-administer-jobs': '*',
    'mapred.queue.default.state': 'RUNNING',
    'mapred.queue.names': 'default',
    'mapred.reduce.child.log.level': 'INFO',
    'mapred.reduce.max.attempts': '4',
    'mapred.reduce.parallel.copies': '5',
    'mapred.reduce.slowstart.completed.maps': '0.05',
    'mapred.reduce.tasks': '1',
    'mapred.reduce.tasks.speculative.execution': 'true',
    'mapred.reducer.class': 'org.apache.hadoop.hive.ql.exec.ExecReducer',
    'mapred.skip.attempts.to.start.skipping': '2',
    'mapred.skip.map.auto.incr.proc.count': 'true',
    'mapred.skip.map.max.skip.records': '0',
    'mapred.skip.reduce.auto.incr.proc.count': 'true',
    'mapred.skip.reduce.max.skip.groups': '0',
    'mapred.submit.replication': '10',
    'mapred.system.dir': '/mapred/system',
    'mapred.task.cache.levels': '2',
    'mapred.task.profile': 'false',
    'mapred.task.profile.maps': '0-2',
    'mapred.task.profile.reduces': '0-2',
    'mapred.task.timeout': '600000',
    'mapred.task.tracker.http.address': '0.0.0.0:50060',
    'mapred.task.tracker.report.address': '127.0.0.1:0',
    'mapred.task.tracker.task-controller': 'org.apache.hadoop.mapred.DefaultTaskController',
    'mapred.tasktracker.dns.interface': 'default',
    'mapred.tasktracker.dns.nameserver': 'default',
    'mapred.tasktracker.expiry.interval': '600000',
    'mapred.tasktracker.indexcache.mb': '10',
    'mapred.tasktracker.instrumentation': 'org.apache.hadoop.mapred.TaskTrackerMetricsInst',
    'mapred.tasktracker.map.tasks.maximum': '6',
    'mapred.tasktracker.reduce.tasks.maximum': '2',
    'mapred.tasktracker.taskmemorymanager.monitoring-interval': '5000',
    'mapred.tasktracker.tasks.sleeptime-before-sigkill': '5000',
    'mapred.temp.dir': '${hadoop.tmp.dir}/mapred/temp',
    'mapred.user.jobconf.limit': '5242880',
    'mapred.userlog.limit.kb': '0',
    'mapred.userlog.retain.hours': '96',
    'mapred.working.dir': 'hdfs://namenodeclustername/user/hive',
    'mapreduce.framework.name': 'classic',
    'mapreduce.ifile.readahead': 'true',
    'mapreduce.ifile.readahead.bytes': '4194304',
    'mapreduce.job.acl-modify-job': '',
    'mapreduce.job.acl-view-job': '',
    'mapreduce.job.cache.files.visibilities': 'true,false,false',
    'mapreduce.job.committer.task.cleanup.needed': 'false',
    'mapreduce.job.complete.cancel.delegation.tokens': 'true',
    'mapreduce.job.dir': 'hdfs://namenodehaclustername/mapred/staging/hive/.staging/job_201304011701_1912',
    'mapreduce.job.map.output.collector.class': 'org.apache.hadoop.mapred.MapTask$MapOutputBuffer',
    'mapreduce.job.maps.speculative.execution': 'false',
    'mapreduce.job.name': 'shib-3578d8d4f5a1812de7a7714f5b108776',
    'mapreduce.job.reduce.shuffle.consumer.plugin.class': 'org.apache.hadoop.mapred.ReduceTask$ReduceCopier',
    'mapreduce.job.reduces.speculative.execution': 'false',
    'mapreduce.job.submithost': '4c3bd1118.livedoor',
    'mapreduce.job.submithostaddress': '10.130.74.79',
    'mapreduce.jobtracker.split.metainfo.maxsize': '10000000',
    'mapreduce.jobtracker.staging.root.dir': '/mapred/staging',
    'mapreduce.map.log.level': 'WARN',
    'mapreduce.map.memory.mb': '1024',
    'mapreduce.reduce.input.limit': '-1',
    'mapreduce.reduce.log.level': 'WARN',
    'mapreduce.reduce.memory.mb': '2048',
    'mapreduce.reduce.shuffle.connect.timeout': '180000',
    'mapreduce.reduce.shuffle.maxfetchfailures': '10',
    'mapreduce.reduce.shuffle.read.timeout': '180000',
    'mapreduce.shuffle.ssl.address': '0.0.0.0',
    'mapreduce.shuffle.ssl.enabled': '${hadoop.ssl.enabled}',
    'mapreduce.shuffle.ssl.port': '50443',
    'mapreduce.tasktracker.cache.local.numberdirectories': '10000',
    'mapreduce.tasktracker.outofband.heartbeat': 'false',
    'net.topology.node.switch.mapping.impl': 'org.apache.hadoop.net.ScriptBasedMapping',
    'net.topology.script.number.args': '100',
    's3.blocksize': '67108864',
    's3.bytes-per-checksum': '512',
    's3.client-write-packet-size': '65536',
    's3.replication': '3',
    's3.stream-buffer-size': '4096',
    's3native.blocksize': '67108864',
    's3native.bytes-per-checksum': '512',
    's3native.client-write-packet-size': '65536',
    's3native.replication': '3',
    's3native.stream-buffer-size': '4096',
    'tasktracker.http.threads': '120',
    'tfile.fs.input.buffer.size': '262144',
    'tfile.fs.output.buffer.size': '262144',
    'tfile.io.chunk.size': '1048576',
    tmpjars: 'file:///home/user/woothee.jar,file:///usr/lib/hive/lib/hive-builtins-0.10.0-cdh4.2.0.jar',
    'user.name': 'hive'
  },
 */